name: 'Stop Action Filter'
description: 'Stops the workflow run if your filter clause evaluates to false'
author: 'Chris McIntosh'
inputs:
  FILTER:
    description: 'The filter clause that you would like to use to filter your jobs'
    required: true
outputs:
  message:
    description: 'Message output. Can be of actions taken or an error message.'
  stepStatus:
    description: 'The status of the current step. Values should be `success` or `failed`.'
runs:
  using: 'node12'
  main: 'dist/index.js'
